/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CaseStudyTurnogoRouteImport } from './routes/case-study.turnogo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudyTurnogoRoute = CaseStudyTurnogoRouteImport.update({
  id: '/case-study/turnogo',
  path: '/case-study/turnogo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/case-study/turnogo': typeof CaseStudyTurnogoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/case-study/turnogo': typeof CaseStudyTurnogoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/case-study/turnogo': typeof CaseStudyTurnogoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/case-study/turnogo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/case-study/turnogo'
  id: '__root__' | '/' | '/case-study/turnogo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CaseStudyTurnogoRoute: typeof CaseStudyTurnogoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-study/turnogo': {
      id: '/case-study/turnogo'
      path: '/case-study/turnogo'
      fullPath: '/case-study/turnogo'
      preLoaderRoute: typeof CaseStudyTurnogoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CaseStudyTurnogoRoute: CaseStudyTurnogoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
